module.exports = Object.freeze([
  "american footballer",
  "archer",
  "athlete",
  "badminton player",
  "baseball player",
  "basketball player",
  "bmx rider",
  "bowler",
  "boxer",
  "cheerleader",
  "club chairman",
  "club chairwoman",
  "club official",
  "club secretary",
  "club treasurer",
  "coach",
  "cricketer",
  "cycler",
  "dancer",
  "darts player",
  "diver",
  "dodgeball player",
  "fan",
  "footballer",
  "gaelic footballer",
  "golfer",
  "handball player",
  "hockey player",
  "horse rider",
  "hurling player",
  "ice hockey player",
  "ice skater",
  "lacrosse player",
  "manager",
  "mma fighter",
  "mountain biker",
  "netball player",
  "polo player",
  "pool player",
  "quidditch player",
  "rock climber",
  "rounders player",
  "rower",
  "rugby player",
  "sailor",
  "skateboarder",
  "skier",
  "skydiver",
  "snooker player",
  "snowboarder",
  "squash player",
  "surfer",
  "swimmer",
  "table tennis player",
  "team leader",
  "team secretary",
  "team treasurer",
  "tennis player",
  "ultimate frisbee player",
  "underwater hockey player",
  "volleyball player",
  "volunteer",
  "water polo player",
  "weightlifter",
  "wrestler",
]);
