module.exports = Object.freeze([
  "American Football",
  "Archery",
  "Athletics",
  "BMX",
  "Badminton",
  "Baseball",
  "Basketball",
  "Bowling",
  "Bowls",
  "Boxing",
  "Cheerleading",
  "Cricket",
  "Curling",
  "Cycling",
  "Dancing",
  "Darts",
  "Diving",
  "Dodgeball",
  "Fencing",
  "Fishing",
  "Football",
  "Gaelic Football",
  "Golf",
  "Handball",
  "Hockey",
  "Horse Riding",
  "Hurling",
  "Ice Hockey",
  "Ice skating",
  "Kayaking or Canoeing",
  "Lacrosse",
  "MMA",
  "Mountain Biking",
  "Netball",
  "Polo",
  "Quidditch",
  "Rock Climbing",
  "Rounders",
  "Rowing",
  "Rugby",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Skiing",
  "Skydiving",
  "Sledging",
  "Snooker or Pool",
  "Snowboarding",
  "Squash",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Ultimate Frisbee",
  "Underwater Hockey",
  "Volleyball",
  "Water Polo",
  "Water Sports",
  "Weightlifting",
  "Wrestling",
]);
